### ISSUE TITLE
sofaboot-sample-standard  demo启动成功，接口访问失败，can not find the corresponding JVM service

### ISSUE THREAD

**Issue by wm5920** [sofastack-guides/sofa-boot-guides#1]
启动项目后，访问 http://localhost:8080/query/1提示

`“{"success":false,"error":"JVM Reference[interface com.alipay.sofa.facade.NewsReadService#] can not find the corresponding JVM service. Please check if there is a SOFA deployment publish the corresponding JVM service. If this exception occurred when the application starts up, please add Require-Module to SOFA deployment's MANIFEST.MF to indicate the startup dependency of SOFA modules."}”`

**Comment by alaneuler** [comment]
用的 sofaboot 是什么版本？启动过程中有错误吗？
我本地试了一下，正常的哦。建议使用 SOFABoot 最新版 3.4.5～

**Comment by wm5920** [comment]
嗯，是启动方式问题，我直接在idea里启动SOFABootWebApplication不行，换成spring-boot:run就可以了
